# supported locales: ru, en
locale: "en"

# Storage type: YAML, H2, MYSQL, MARIADB
storage: H2

database:
  host: localhost
  port: 3306
  database: playergrowth
  username: root
  password: ""
  pool:
    maximum-pool-size: 10
    minimum-idle: 2
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

scale:
  # Initial growth height
  min: 0.3
  # Max Growth height
  max: 1.0
  # Time for max growth height (in minutes)
  time-to-grow: 2880

growth:
  # Enables automatic growth updates
  auto-growth: true
  # Growth update time (in seconds)
  # Very small value may cause performance degradation
  growth-update-time: 5.0